const assert = require('node:assert/strict');
const fs = require('node:fs');
const test = require('node:test');

test('chart page contains data controls and live chart integration', () => {
  const template = fs.readFileSync(require.resolve('../views/charts.ejs'), 'utf8');
  assert.match(template, /id="chart"/);
  assert.match(template, /candles\/snapshot/);
  assert.match(template, /candles\/live/);
  assert.match(template, /payload\.candlestick/);
  assert.match(template, /stopLiveUpdates/);
  assert.match(template, /indicators=/);
  assert.match(template, /openTime/);
  assert.match(template, /indicator/);
  assert.match(template, /strategy-selector/);
  assert.match(template, /api\/v1\/strategy\/status/);
  assert.match(template, /api\/v1\/strategy\/decisions/);
  assert.match(template, /setMarkers/);
  assert.match(template, /selected\.indicators.*join/);
  assert.match(template, /paneIndexes/);
  assert.match(template, /indicator\.placement/);
  assert.match(template, /seriesByKey/);
  assert.match(template, /addSeries\(LightweightCharts\.LineSeries/);
  assert.match(template, /addSeries\(LightweightCharts\.HistogramSeries/);
  assert.match(template, /priceFormat: \{ type: 'volume' \}/);
  assert.match(template, /volumePaneIndex/);
  assert.match(template, /setHeight\(140\)/);
  assert.match(template, /volumeSeries\.update/);
  assert.match(template, /type: 'volume'/);
  assert.match(template, /separatorColor/);
  assert.match(template, /chart-pane-label/);
  assert.match(template, /indicatorLabel/);
  assert.match(template, /clearPaneLabels/);
  assert.match(template, /id="pane-labels"/);
  assert.match(template, /id="pane-dividers"/);
  assert.match(template, /chart-pane-divider/);
  assert.match(template, /getBoundingClientRect/);
  assert.match(template, /positionPaneLabels/);
  assert.match(template, /schedulePaneLabelPosition/);
  assert.match(template, /requestAnimationFrame/);
  assert.match(template, /cancelAnimationFrame/);
  assert.match(template, /paneLabelCreationFrame/);
  assert.match(template, /schedulePaneLabelCreation/);
  assert.match(template, /paneResizeObservers/);
  assert.match(template, /panePriceScaleAtPoint/);
  assert.match(template, /scalePriceFromWheel/);
  assert.match(template, /setVisibleRange/);
  assert.match(template, /capture: true/);
  assert.match(template, /separatorColor: '#64748b'/);
  assert.match(template, /separatorHoverColor: '#334155'/);
  assert.doesNotMatch(template, /separatorColor: '#ffffff'/);
  assert.match(template, /pointer-events: none/);
  assert.match(template, /positionPaneDividers/);
  assert.doesNotMatch(template, /borderTop = '16px solid #ffffff'/);
});
